=== NKanthi/SampleProject/XML/1811-xander/XML/schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="phones">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="phone">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="model_simple" type="xs:string"/>
                            <xs:element name="model_complex" type="xs:string"/>
                            <xs:element name="CPU_model" type="xs:string"/>
                            <xs:element name="RAM" type="xs:string"/>
                            <xs:element name="storage" type="xs:string"/>
                            <xs:element name="price" type="xs:int">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="150"/>
                                        <xs:maxInclusive value="1800"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="model"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== NKanthi/SampleProject/XML/1811-xander/XML/phonelist.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="phonestyle.xsl"?>

<phones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <phone model="S88">
        <model_simple>Samung S88</model_simple>
        <model_complex>GR89123HAZ</model_complex>
        <CPU_model>Snap dragon infinity fabric</CPU_model>
        <RAM>1TB</RAM>
        <storage>24PB</storage>
        <price>780</price>
    </phone>

    <phone model="X5s">
        <model_simple>Iphone X5s</model_simple>
        <model_complex>IOS12848_ST-EV-E-JO-BS</model_complex>
        <CPU_model>Qualcom-Z</CPU_model>
        <RAM>500GB</RAM>
        <storage>12PB</storage>
        <price>1560</price>
    </phone>
</phones>
